uint8 PATTERN_ON=255
uint8 PATTERN_FLASH=15
uint8 PATTERN_DFLASH=9
uint8 PATTERN_QUICKFLASH=1
uint8 PATTERN_OFF=0

uint8 position_light    # Signal the status of the GPS system
uint8 autopilot_light   # Signal if the system is under automatic or manual control
uint8 beacon     # Overhead beacon flash pattern
uint8 headlight  # Headlight flash pattern
uint8 taillight  # Taillight flash pattern
uint8 beep   # Noisemaker sound pattern
