<?xml version="1.0"?>
<!--
Copyright (c) 2012, Siddhant Ahuja (Sid), Ryan Gariepy
Copyright (c) 2014, Clearpath Robotics
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Clearpath Robotics nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This program contains the description of the robot base model for the Clearpath Grizzly
-->

<robot name="rambler" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find agv_description)/urdf/materials.urdf.xacro" />
  <xacro:include filename="$(find agv_description)/urdf/wheel.urdf.xacro" />


  <!-- Key Dimensions -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="ground_clearance" value=".07" />
  <xacro:property name="base_length" value="0.491" />
  <xacro:property name="base_width" value="0.44" />
  <xacro:property name="base_height" value="0.125" />
  <xacro:property name="base_mass" value="30" />
  <xacro:property name="scale" value="0.001"/>

  <xacro:property name="base_x_origin_to_wheel_origin" value="0.163" /> <!-- 203.2/2 + 500/2 +/-tolerance -->
  <xacro:property name="base_y_origin_to_wheel_origin" value="0.25" /> <!--(70)/4 + 440/2 +/-tolerance -->
  <xacro:property name="base_z_origin_to_wheel_origin" value="0.1" />

  <link name="root_link" />

  <link name="base_link">
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 ${ground_clearance+base_height/2}"/>
      <inertia ixx= "1.000000" ixy= "-0.000000" ixz="0.000000" iyy="1.000000" iyz="0.000000" izz="1.000000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${ground_clearance+base_height/2}"
              rpy="${M_PI/2} 0 0"/>
      <geometry>
        <mesh filename="package://agv_description/meshes/bot.stl" scale="${scale} ${scale} ${scale}" />
      </geometry>
      <material name="Grey" />
    </visual>
    <collision>
      <origin xyz="0 0 .123"
              rpy="0 0 0"/>
      <geometry>
         <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
  </link>
  <joint name="root_joint"
         type="fixed">
    <origin xyz="0 0 ${ground_clearance}"
            rpy="0 0 0"/>
    <parent link="root_link" />
    <child link="base_link" />
  </joint>

  <!--Add a sensor anchor link that points to the center of the robot top plate
   <link name="sensor_anchor_link"/>
  <joint name="sensor_anchor_joint" type="fixed">
    <origin xyz="0 0 0"
            rpy="0 0 0" />
    <parent link="base_link" />
    <child link="sensor_anchor_link" />
  </joint>-->

  <agv_wheel fr="front" lr="left" parent="base_link" translateX="1" translateY="1" flipY="0" />
  <agv_wheel fr="front" lr="right" parent="base_link" translateX="1" translateY="-1" flipY="1" />
  <agv_wheel fr="rear" lr="left" parent="base_link" translateX="-1" translateY="1" flipY="0" />
  <agv_wheel fr="rear" lr="right" parent="base_link" translateX="-1" translateY="-1" flipY="1" />
</robot>
